# PH section
- alias: ph_start
  id: '1559669855764'
  initial_state: true
  trigger:
  - platform: state
    entity_id: switch.ph
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.pump
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.ph

- alias: ph_high
  id: '1559049859759'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.ph
    above: 7.5
    for:
      hours: 48
  condition: []
  action:
  - data_template:
      message: '{{trigger.to_state.attributes.friendly_name}}: {{trigger.to_state.state}}'
      title: 'pH high ({{trigger.to_state.state}})!'
    service: notify.notify

- alias: ph_low
  id: '1559049839760'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.ph
    below: 6.9
    for:
      hours: 48
  condition: []
  action:
  - data_template:
      message: '{{trigger.to_state.attributes.friendly_name}}: {{trigger.to_state.state}}'
      title: 'pH low ({{trigger.to_state.state}})!'
    service: notify.notify

- alias: ph_bad
  id: '1559049893756'
  initial_state: true
  trigger:
  - platform: template
    value_template: '{{state_attr("sensor.ph", "standard_deviation") > 0.1}}'
  condition: []
  action:
  - service: notify.notify
    data_template:
      message: 'It varied between {{state_attr("sensor.ph", "min_value")}} and 
        {{state_attr("sensor.ph", "max_value")}} over the past 
        {{(state_attr("sensor.ph", "sampling_size")*30/60)|int}} minutes'
        # scan_interval: 30 is the scan_interval for the orp probe (orp.yaml) 
      title: 'pH probe may need calibration!'
  - service: automation.turn_off
    entity_id: automation.ph_bad

- alias: ph_target
  id: '1559146893656'
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_number.ph_target
  condition: []
  action:
    - service: automation.trigger
      entity_id: automation.muriatic_set

# ORP section
- alias: orp_start
  id: '1559639825764'
  initial_state: true
  trigger:
  - platform: state
    entity_id: switch.orp
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.pump
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.orp

- alias: orp_bad
  id: '1559149493756'
  initial_state: true
  trigger:
  - platform: template
    value_template: '{{state_attr("sensor.orp", "standard_deviation") > 20 }}'
  condition: []
  action:
  - service: notify.notify
    data_template:
      message: 'It varied between {{state_attr("sensor.orp", "min_value")}} and 
        {{state_attr("sensor.orp", "max_value")}} over the past 
        {{(state_attr("sensor.orp", "sampling_size")*30/60)|int}} minutes'
        # scan_interval: 30 is the scan_interval for the orp probe (orp.yaml) 
      title: 'ORP probe may need calibration!'
  - service: automation.turn_off
    entity_id: automation.orp_bad

#FC Section
- alias: fc_ok
  id: '1559638825701'
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.e_fc
    above: 0.60
    below: 5.00
    for:
      minutes: 1
  condition: []
  action:
  - service: frontend.set_theme
    data:
      name: default
- alias: fc_high
  id: '1559638825702'
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.e_fc
    above: 5.01
    for:
      minutes: 1
  condition: []
  action:
  - service: frontend.set_theme
    data:
      name: danger


- alias: fc_low
  id: '1559638825703'
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.e_fc
    below: 0.59
    for:
      minutes: 1
  condition: []
  action:
  - service: frontend.set_theme
    data:
      name: algae


- alias: fc_target
  id: '1559146873657'
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_number.fc_target
  condition: []
  action:
    - service: automation.trigger
      entity_id: automation.bleach_set



# Flow Section
- alias: notify_cummulated_flow
  id: '1559049859380'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.remain_cycles
    below: 1
  condition:
  - condition: numeric_state
    entity_id: input_number.notify_cycles
    above: 0
  action:
  - data_template:
      message: "in low speed: {{state_attr('sensor.cummulated_flow_low','value')}}{{'\n'}}in high speed: {{state_attr('sensor.cummulated_flow_high','value')}}{{'\n'}}@{{now().strftime('%H:%M')}}[{{now().day}}/{{now().month}}]"
      title: "Flow: {{states('input_number.notify_cycles')|int}} cycles reached!"
    service: notify.notify

- alias: reset_cummulated_flow_start
  id: '1559293506609'
  trigger: []
  condition: []
  action:
  - service: input_datetime.set_datetime
    data_template:
      entity_id: input_datetime.cummulated_flow_start
      date: "{{now().timestamp()|timestamp_custom('%Y-%m-%d', True)}}"
      time: "{{now().timestamp()|timestamp_custom('%H:%M:%S', True)}}"

- alias: winter_session
  id: '1559049956784'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: input_number.cycle
    below: 240
    for:
      hours: 121
  condition:
  - condition: state
    entity_id: input_boolean.notify_seasson
    state: 'on'
  action:
  - data_template:
      message: "@{{now().strftime('%H:%M')}}[{{now().day}}/{{now().month}}]"
      title: 'Winter is comming!'
    service: notify.notify

- alias: summer_session
  id: '1559049956785'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: input_number.cycle
    above: 240
    for:
      hours: 121
  condition:
  - condition: state
    entity_id: input_boolean.notify_seasson
    state: 'on'
  action:
  - data_template:
      message: "@{{now().strftime('%H:%M')}}[{{now().day}}/{{now().month}}]"
      title: "Summer is here!"
    service: notify.notify

- alias: factory_started
  id: '1559149839000'
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  condition: 
    condition: state 
    entity_id: input_boolean.factory_started
    state: 'off'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.factory_started
  - service: input_number.set_value
    data_template:
      entity_id: input_number.capacity_metric
      value: 50
  - service: input_number.set_value
    data_template:
      entity_id: input_number.quality
      value: 4
  - service: input_number.set_value
    data_template:
      entity_id: input_number.bleach_tank
      value: 20
  - service: input_number.set_value
    data_template:
      entity_id: input_number.bleach_concentration
      value: 5
  - service: input_number.set_value
    data_template:
      entity_id: input_number.bleach_speed
      value: 25
  - service: input_number.set_value
    data_template:
      entity_id: input_number.fc_target
      value: 1.5
  - service: input_number.set_value
    data_template:
      entity_id: input_number.e_fc_adjust
      value: 0
  - service: input_number.set_value
    data_template:
      entity_id: input_number.ph_target
      value: 7.2
  - service: input_number.set_value
    data_template:
      entity_id: input_number.muriatic_tank
      value: 10
  - service: input_number.set_value
    data_template:
      entity_id: input_number.muriatic_concentration
      value: 20
  - service: input_number.set_value
    data_template:
      entity_id: input_number.muriatic_speed
      value: 25
  - service: input_datetime.set_datetime
    data_template:
      entity_id: input_datetime.recirculation
      time: 08:00:00

