homeassistant:
  name: RaspiPool
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: imperial
  # customize: !include customize.yaml
  packages: !include_dir_named packages
  external_url: "http://ivmcontrol.dscloud.me:8123"
  internal_url: "http://homeassistant.local:8123"
default_config:
# Disable Discover some devices automatically
# discovery:
tts:
  - platform: google_translate
logger:
  default: info
  logs:
    custom_components.atlas_scientific.sensor: debug
    homeassistant.components.sensor.atlas_scientific: debug
    homeassistant.components.switch.command_line: debug
    zeroconf: error
    homeassistant.components.websocket_api.http.connection: error

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
lovelace:
  mode: yaml
shell_command:
  calibrate: 'python calibrate.py "{{ device }}" "{{ target }}"'
system_log:
   max_entries: 500
