title: Raspipool
views:
  - badges:
      - sensor.exterior_temperature
      - sensor.e_fc
      - sensor.cycle_pool
      - sensor.exterior_condition
    title: Pool
    panel: false
    icon: 'mdi:pool'
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - max: 90
                min: 32
                theme: Backend-selected
                entity: sensor.pool_water_temperature
                severity:
                  red: 32
                  green: 60
                  yellow: 84
                name: Temp
                type: gauge
              - max: 8.5
                min: 6.5
                theme: Backend-selected
                entity: sensor.ph
                severity:
                  yellow: 6.8
                  green: 7.2
                  red: 7.8
                name: pH
                type: gauge
              - max: 1200
                min: 0
                theme: Backend-selected
                entity: sensor.orp
                severity:
                  green: 500
                  yellow: 800
                  red: 100
                name: ORP
                type: gauge
          - show_name: false
            entities:
              - entity: sensor.ezo_temperature
                hold_action:
                  action: call-service
                  service: homeassistant.update_entity
                  service_data:
                    entity_id: sensor.ezo_temperature
              - entity: sensor.ezo_ph
                hold_action:
                  action: call-service
                  service: homeassistant.update_entity
                  service_data:
                    entity_id: sensor.ezo_ph
              - entity: sensor.ezo_orp
                hold_action:
                  action: call-service
                  service: homeassistant.update_entity
                  service_data:
                    entity_id: sensor.ezo_orp
            type: glance
            show_state: true
          - title: Supplies
            type: horizontal-stack
            cards:
              - max: 20
                min: 0
                theme: default
                entity: sensor.remain_cycles
                severity:
                  green: 15
                  red: 5
                  yellow: 10
                name: remain cycles
                type: gauge
              - max: 10
                min: 0
                theme: default
                entity: sensor.muriatic_tank
                severity:
                  green: 5
                  red: 1
                  yellow: 3
                type: gauge
              - max: 15
                min: 0
                theme: default
                entity: sensor.bleach_tank
                severity:
                  green: 8
                  red: 0
                  yellow: 3
                type: gauge
          - show_name: true
            entities:
              - entity: switch.pump
                icon: mdi:engine
                hold_action:
                  action: toggle
              - entity: switch.turbo
                icon: mdi:speedometer
                hold_action:
                  action: toggle
              - entity: binary_sensor.muriatic
                hold_action:
                  action: call-service
                  service: switch.toggle
                  service_data:
                    entity_id: switch.ph
                tap_action:
                  action: navigate
                  navigation_path: /lovelace/2
              - entity: binary_sensor.bleach
                hold_action:
                  action: call-service
                  service: switch.toggle
                  service_data:
                    entity_id: switch.orp
                tap_action:
                  action: navigate
                  navigation_path: /lovelace/2
            type: glance
            show_state: false
            show_icon: true
  - badges: []
    title: History
    icon: 'mdi:chart-line'
    cards:
          - title: last 3 hours
            entities:
              - entity: sensor.pump_state
              - entity: switch.orp
                name: Bleach inj.
              - entity: switch.ph
                name: Muriatic inj.
              - entity: sensor.ph
                name: pH
              - entity: sensor.orp
                name: ORP
              - entity: sensor.pool_temp_fahrenheit
                name: Water Temp.
            type: history-graph
            hours_to_show: 3
          - title: last 3 days
            entities:
              - entity: sensor.pump_state
              - entity: switch.orp
                name: Bleach inj.
              - entity: switch.ph
                name: Muriatic inj.
              - entity: sensor.ph
                name: pH
              - entity: sensor.orp
                name: ORP
              - entity: sensor.pool_temp_fahrenheit
                name: Water Temp.
            type: history-graph
            hours_to_show: 72
  - badges: []
    title: Chemical
    icon: 'mdi:flask'
    cards:
          - title: Muriatic Acid ( - pH )
            entities:
              - entity: input_number.muriatic_tank
                name: Tank level
              - entity: input_number.muriatic_concentration
                name: Concentration
              - entity: input_number.muriatic_speed
                name: Speed injection
              - entity: switch.ph
                name: Pump injection
                secondary_info: last-changed
              - entity: input_boolean.lock_muriatic
                name: Disable Automatic Injection
            type: entities
            show_header_toggle: false
          - title: Bleach ( + ORP )
            entities:
              - entity: input_number.bleach_tank
                name: Tank level
              - entity: input_number.bleach_concentration
                name: Concentration
              - entity: input_number.bleach_speed
                name: Speed injection
              - entity: switch.orp
                name: Pump injection
                secondary_info: last-changed
              - entity: input_boolean.lock_bleach
                name: Disable Automatic Injection
            type: entities
            show_header_toggle: false
  - badges: []
    path: default_view
    icon: 'mdi:message-alert'
    title: Alerts
    cards:
      - title: Notifications
        entities:
          - entity: input_number.notify_cycles
          - entity: input_boolean.notify_seasson
          - entity: input_number.notify_muriatic_high
          - entity: input_number.notify_muriatic_tank
          - entity: input_number.notify_bleach_tank
          - entity: input_number.notify_bleach_high
        type: entities
        show_header_toggle: true
  - badges: []
    title: Settings
    icon: 'mdi:tune'
    cards:
      - title: Pool Settings
        entities:
          - label: Pool
            type: section
          - entity: input_number.capacity
            name: Capacity
          - entity: input_number.quality
            name: Quality
          - entity: input_datetime.recirculation
            name: Turnover rate
          - entity: input_boolean.turbo
          - entity: input_number.turbo
          - label: Filter
            type: section
          - entity: input_datetime.cycle_start
          - entity: input_number.second_cycle
          - entity: sensor.cycle_pool
          - entity: input_number.cycle
        type: entities
        show_header_toggle: false
        theme: default
      - title: Chemical settings
        entities:
          - label: Free Chlorine (FC)
            type: section
          - entity: input_number.fc_target
            name: FC target
          - entity: sensor.e_fc
            name: FC actual
          - entity: input_number.bleach_inject
            name: Next bleach injection (ml)
          - entity: input_number.e_fc_adjust
            name: Adjust ±% FC-ORP
          - label: pH
            type: section
          - entity: input_number.ph_target
            name: pH target
          - entity: sensor.ph
            name: pH actual
          - entity: input_number.muriatic_inject
            name: Next muriatic injection (ml)
        type: entities
        show_header_toggle: false
  - badges:
      - sun.sun
      - sensor.time
      - sensor.cycle_pool
      - input_number.out_of_order
    title: Advanced
    icon: 'mdi:cog'
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title: Hold down to activate
            cards:
              - icon_height: 64px
                type: entity-button
                tap_action:
                  action: none
                entity: input_number.out_of_order
                show_name: true
                name: Maintenance
                show_icon: true
                hold_action:
                  action: more-info
              - icon_height: 64px
                type: entity-button
                tap_action:
                  action: more-info
                entity: input_datetime.cummulated_flow_start
                show_name: true
                name: Reset Cumm. Flow
                show_icon: true
                hold_action:
                  action: call-service
                  service: automation.trigger
                  service_data:
                    entity_id: automation.reset_cummulated_flow_start
              - icon_height: 64px
                type: entity-button
                tap_action:
                  action: none
                entity: input_number.boost_for
                show_name: true
                name: Boost
                show_icon: true
                hold_action:
                  action: more-info
          - entities:
              - entity: input_datetime.cummulated_flow_start
              - entity: sensor.cummulated_flow_high
              - entity: sensor.cummulated_flow_low
            type: entities
          - title: Calibrate Sensors
            type: horizontal-stack
            cards:
              - icon_height: 64px
                type: entity-button
                entity: input_number.calibrate_ph
                show_name: true
                name: pH
                show_icon: true
                show_state: true
                hold_action:
                  action: call-service
                  confirmation:
                    text: Are you sure you want to calibrate?
                  service: script.calibrate_ph
                footer:
                  type: markdown
                  content: note
              - icon_height: 64px
                type: entity-button
                entity: input_number.calibrate_orp
                show_name: true
                name: ORP
                show_icon: true
                show_state: true
                hold_action:
                  action: call-service
                  confirmation:
                    text: Are you sure you want to calibrate?
                  service: script.calibrate_orp
              - icon_height: 64px
                type: entity-button
                entity: input_number.calibrate_temp
                show_name: true
                name: Temp
                show_icon: true
                show_state: true
                hold_action:
                  action: call-service
                  confirmation:
                    text: Are you sure you want to calibrate?
                  service: script.calibrate_temp

