title: Sparkly

kiosk_mode:
  hide_overflow: true
  hide_sidebar: false
# make it stand alone
#  hide_sidebar: true

views:
  - !include dashboard/main.yaml
  - !include dashboard/advanced.yaml
  - !include dashboard/chemicals.yaml
  - !include dashboard/history.yaml
  - !include dashboard/settings.yaml
