sensor:
  - platform: template
    sensors:
      bleach_tank:
        friendly_name: "Bleach tank"
        value_template: "{{ states('input_number.bleach_tank')|round(2)}}"

  - platform: history_stats
    name: bleach_on_last_hour
    entity_id: switch.orp
    state: 'on'
    type: time
    end: '{{now().replace(minute=0).replace(second=0)}}'
    duration: 01:00:00

  - platform: history_stats
    name: bleach_on_last_48h
    entity_id: switch.orp
    state: 'on'
    type: time
    end: '{{now()}}'
    duration: 48:00:00

input_number:
  bleach_tank:
    min: 0
    max: 76
    step: 0.1
    unit_of_measurement: 'l'
    icon: mdi:blood-bag
    name: Sanitizer Tank
    mode: box
  bleach_tank_imperial:
    min: 0
    max: 20
    step: 0.1
    unit_of_measurement: 'gal'
    icon: mdi:blood-bag
    name: Sanitizer Tank
    mode: box
  bleach_concentration:
    min: 1
    max: 15
    step: .25
    unit_of_measurement: '%'
    icon: mdi:water-percent
  bleach_speed:
    min: 0
    max: 263
    step: 1
    unit_of_measurement: 'ml/min'
    icon: mdi:needle
    mode: box
  bleach_speed_imperial:
    min: 0.1
    max: 100
    step: 0.1
    unit_of_measurement: 'gal/day (GPD)'
    icon: mdi:needle
    mode: box
  notify_bleach_high:
    name: Chlorine Overfeed
    min: 0
    max: 15
    step: 0.1
    unit_of_measurement: 'l/48h'
  notify_bleach_tank:
    name: Chlorine Tank Low
    min: 0
    max: 5
    step: 0.5
    unit_of_measurement: 'l'
    icon: mdi:flask-empty-outline
  bleach_inject:
    min: 0
    max: 20000
    step: 5
    unit_of_measurement: 'ml'
    icon: mdi:beaker
    mode: box

automation:
  - alias: bleach_sync_1
    trigger:
      - platform: state
        entity_id: input_number.bleach_tank
    condition: []
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bleach_tank_imperial
          value: "{{(states('input_number.bleach_tank')|float / 3.78541)| round(1) }}"

  - alias: bleach_sync_2
    trigger:
      - platform: state
        entity_id: input_number.bleach_tank_imperial
    condition: []
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bleach_tank
          value: "{{(states('input_number.bleach_tank_imperial')|float * 3.78541)| round(1) }}"

  - alias: bleach_inj_sync_1
    trigger:
      - platform: state
        entity_id: input_number.bleach_speed
    condition: []
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bleach_speed_imperial
          value: "{{(states('input_number.bleach_speed')|float / 2.6287)| round(1) }}"

  - alias: bleach_inj_sync_2
    trigger:
      - platform: state
        entity_id: input_number.bleach_speed_imperial
    condition: []
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bleach_speed
          value: "{{(states('input_number.bleach_speed_imperial')|float * 2.6287)| round(1) }}"
