sensor:
# Estimated sensor of effective Free Chlorine
  - platform: template
    sensors:
      e_fc:
        value_template: >-
          {{ (0.23 * (1 + states('input_number.e_fc_adjust')|float / 100 ) *
          ( 14 - states('sensor.ph')|float) ** ( 1 / (400 - states('sensor.orp')|float) ) *
          ([4.2, states('sensor.ph')|float]|max - 4.1) ** ( ( states('sensor.orp')|float - 516)/145) +
          10.0 ** ( (states('sensor.orp')|float + states('sensor.ph')|float * 70 - 1282) / 40 ) ) |round(1) }}
        unit_of_measurement: ppm
        icon_template: mdi:react
        friendly_name: "Estimated FC"
        # TODO: This can determine an error:
        # ZeroDivisionError: 0.0 cannot be raised to a negative power
        # ([4.1, states('sensor.ph')|float]|max - 4.1) ** ( ( states('sensor.orp')|float - 516)/145)

input_number:
  e_fc_adjust:
    min: -100
    max: 100
    unit_of_measurement: '%'
    icon: mdi:react
    mode: box
  fc_target:
    min: 0
    max: 30
    step: 0.1
    mode: box
    unit_of_measurement: 'ppm'
    icon: mdi:react

automation:
  - alias: fc_ok
    trigger:
      platform: numeric_state
      entity_id: sensor.e_fc
      above: 0.60
      below: 5.00
      for:
        minutes: 1
    condition: []
    action:
    - service: frontend.set_theme
      data:
        name: default
  - alias: fc_high
    trigger:
      platform: numeric_state
      entity_id: sensor.e_fc
      above: 5.01
      for:
        minutes: 1
    condition: []
    action:
    - service: frontend.set_theme
      data:
        name: danger

  - alias: fc_low
    trigger:
      platform: numeric_state
      entity_id: sensor.e_fc
      below: 0.59
      for:
        minutes: 1
    condition: []
    action:
    - service: frontend.set_theme
      data:
        name: algae

  - alias: fc_target
    trigger:
      - platform: state
        entity_id: input_number.fc_target
    condition: []
    action:
      - service: automation.trigger
        entity_id: automation.bleach_set
