sensor:
  - platform: statistics
    name: orp
    entity_id: sensor.ezo_orp
    max_age:
      minutes: 60
    precision: 0

  - platform: atlas_scientific
# For serial ports use:
#   port: /dev/ttyUSB0
# For I2C enter the hex device id
    port: 0x62
#    offset: 78
    scan_interval: 10

automation:
- alias: orp_start
  id: '1559639825764'
  initial_state: true
  trigger:
  - platform: state
    entity_id: switch.orp
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.pump
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.orp

- alias: orp_bad
  id: '1559149493756'
  initial_state: true
  trigger:
  - platform: template
    value_template: '{{state_attr("sensor.orp", "standard_deviation") > 20 }}'
  condition: []
  action:
  - service: notify.pushbullet
    data_template:
      message: 'Between {{state_attr("sensor.orp", "min_value")}} and {{state_attr("sensor.orp", "max_value")}}{{- "\n\n" -}}@{{now().strftime("%H:%M")}}[{{now().day}}/{{now().month}}]'
      title: 'ORP probe bad (calibrate?) !!!'
  - service: automation.turn_off
    entity_id: automation.orp_bad


