sensor:
  - platform: statistics
    name: orp
    entity_id: sensor.ezo_orp
    max_age:
      minutes: 60
    precision: 0

  - platform: atlas_scientific
# For serial ports use:
#   port: /dev/ttyUSB0
# For I2C enter the hex device id
    port: 0x62
#    offset: 78
    scan_interval: 10

input_number:
  calibrate_orp:
    min: 100
    max: 1500
    step: 1
    unit_of_measurement: 'mV'
    icon: mdi:water-percent
    mode: box
    initial: 700

