input_datetime:
  cycle_start:
    name: Pump cycle start time
    has_date: false
    has_time: true
  recirculation:
    name: Recirculation cycle
    has_time: true
    has_date: false
    icon: mdi:timer-outline


input_number:
  capacity_imperial:
    name: Pool Capacity (gal)
    min: 1000
    max: 50000
    step: 1000
    unit_of_measurement: gal
    icon: mdi:water-pump
    mode: box
  capacity_metric:
    name: Pool Capacity (m³)
    min: 5
    max: 100
    unit_of_measurement: m³
    icon: mdi:water-pump
    mode: box
  quality:
    name: Water Quality
    min: 0
    max: 9
    unit_of_measurement: stars
    icon: mdi:star
  turbo:
    name: '% in high speed'
    min: 0
    max: 100
    step: 5
    unit_of_measurement: '%'
    icon: mdi:circle-slice-2


input_boolean:
  turbo:
    name: Dual-speed Pump
    icon: mdi:play-speed
  
  factory_started:
    name: Factory config started
    icon: mdi:auto-fix

# should we use imperial units or metric?
# see issue #1
  imperial:
    name: Imperial Units
    icon: mdi:tape-measure
    initial: true

  salt_system:
    name: Salt System
    icon: mdi:shaker-outline
    initial: false

sensor:
  - platform: template
    sensors:
      capacity_uom:
        value_template: >-
          {% if is_state("input_boolean.imperial", "on") -%}
            gal
          {%- else -%}
            l
          {%- endif %}