sensor:
  - platform: template
    sensors:
      pool_temp:
        friendly_name: "Water Temperature"
        entity_id: sensor.pool_temp_fahrenheit
        value_template: "{{ ((states('sensor.pool_temp_fahrenheit')|float - 32)*5/9)|round(1) }}"
        icon_template: mdi:coolant-temperature
        unit_of_measurement: '째C'

  - platform: template
    sensors:
      pool_temp_fahrenheit:
        friendly_name: "Water Temperature"
        entity_id: sensor.pool_water_temperature
        value_template: "{{ states('sensor.pool_water_temperature')|float|round(1) }}"
        icon_template: mdi:coolant-temperature
        unit_of_measurement: '째F'
#  - platform: onewire
#    names:
#      28-0319a2792bc3: Pool water
#    scan_interval: 10

# Atlas Resistance Temperature Detector (RTD)
  - platform: atlas_scientific
# For serial ports use:
#   port: /dev/ttyUSB0
# For I2C enter the hex device id
    port: 0x66
    scan_interval: 30
    scale: '째F'

  - platform: statistics
    name: pool_water_temperature
    entity_id: sensor.ezo_temperature
    max_age:
      minutes: 60
    precision: 1

input_number:
  calibrate_temp:
    min: 40
    max: 90
    step: 1
    unit_of_measurement: '째F'
    icon: mdi:coolant-temperature
    mode: box
    initial: 70
